database:
    host: 127.0.0.1
    port: 3306
    username: root
    password: '12345678'
    database: test
    charset: utf8
    collation: utf8_general_ci

jwt:
    secret: 'secret'
    expiresIn: '24h'
